name: GitHub Actions Demo

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - run: | 
           echo "Event that triggered the wf was: ${{github.event_name}}"
           echo "Wf triggered by branch ${{github.branch}}

      - uses: actions/checkout@v3.3.0
      
      - name : List all files of the repo
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
      
