name: Hello world docker image

on:
  push:
    branches:
      - main
    paths:
      - "hello-world-docker-action/**"
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3.3.0

      - name: Run my created container action in this workflow
        uses: ./hello-world-docker-action
        id: hello-docker-action
        with:
          who-to-greet: ${{ github.user }}

      - name: Echo output time from docker container
        run: |
          echo "output time was ${{ steps.hello-docker-action.outputs.time }}"
